#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

STDIN=$(cat)
APP="$1"
PERSISTENT_FILE="PERSISTENT_STORAGE"
PERSISTENT_FILE_PATH="$DOKKU_ROOT/$APP/$PERSISTENT_FILE"

output=""
if [[ -f "$PERSISTENT_FILE_PATH" ]]; then
  DONE=false
  until $DONE; do
    read line || DONE=true
    # echo $line
    [[ ! -n "$line" ]] && continue
    case "$line" in
      \#*)
        continue
        ;;
      *)
        output="$output -v $line"
        ;;
    esac
  done < $PERSISTENT_FILE_PATH
fi

echo "$STDIN$output"
